### PR TITLE
generalize shutter_mode

### LINKED ISSUE #212: more about shutter_mode (for Rigaku)
In #200, the two modes for `shutter_mode` were defined.  It was determined that `shutteroff` is a no-op so can be removed.  Also, `shutter_mode` is more general than just UFXC, so move (?) that bit of code out of rigaku support and into shutters?

### PR DESCRIPTION
**Pull request by prjemian**
fixes #212

### CODE REVIEW

**Comment by prjemian** [comment]
@sureshnaps Please check these meager changes to make sure they seem reasonable.

**Comment by prjemian** [comment]
since this PR was made ready, master has moved on so there are conflicts.

**Comment by prjemian** [comment]
Should this be closed without merge?

**Comment by qzhang234** [comment]
Yes, it can be closed without merge.

**Pull request closed without merging**
