### PR TITLE
clarify file paths in AD_Acquire()

### PR DESCRIPTION
**Pull request by prjemian**
- #293

### CODE REVIEW

**Comment by prjemian** [comment]
@qzhang234 We should talk about this before merging.  There is still a major part we need to examine.  It needs the actual PVs to resolve.

**Comment by qzhang234** [comment]
I agree. How about next Thursday?

In the meantime I'll run the stability test on Monday and Tuesday when beam is down using Suresh's implementation

**Comment by prjemian** [comment]
Sure, the usual time? Detector will be available then?

**Comment by prjemian** [comment]
Need all changes in the 150-lambda2m branch pushed first.

**Pull request merged**
