### PR TITLE
support APS data management

### LINKED ISSUE #25: handle metadata per initial request
Per initial request in #9, handle the existing metadata.

* [x] create `ophyd.Device` to connect with metadata PVs
* [x] bluesky plan to write HDF5 file with DataExchange schema
* [x] function to launch data management tools as external process

### LINKED ISSUE #31: subclass EpicsSignal for batch_pars items
As part of #25, create a subclass of `ophyd.EpicsSignal` for the items of the `batch_pars` list used in SPEC now.  Need additional terms for `label`, `h5address`, maybe some others, too.  That's a start.

### PR DESCRIPTION
**Pull request by prjemian**
fixes #25, fixes #31

### CODE REVIEW

**Comment by sureshnaps** [comment]
The code changes looked ok but the new test.h5 still has integers for the fields. sample/orientation pitch, roll, yaw is fixed and so is detector/lld but not the rest.

**Comment by prjemian** [comment]
Wondering if those fields are still integers because of their representation in detectorinfo.m?  If there is no ".", they are interpreted as integer.  Surprised the `dtype='float64'` did not override.
https://github.com/aps-8id-trr/ipython-8idiuser/blob/29be31600f815fbf6e4648d4a970b6eaef4961b5/profile_bluesky/startup/spec_support/detector_parameters.py#L68-L71

**Comment by prjemian** [comment]
They will be forced to `float()` in addition to `dtype='float64'`

**Comment by sureshnaps** [comment]
now this makes sense. For this data, geometry=0, so the default -1 was called. For data when geometry=1, then the code that used dtype would have been called and that would have come ok. So this is all good and can be merged and closed.

**Comment by prjemian** [comment]
We made the requested changes but need to learn how to mark a review as accepted.  Merging this PR now, can learn how to accept next time.

**Pull request merged**
