### PR TITLE
refactor DM support so it can be called from bluesky or pyepics

### LINKED ISSUE #36: refactor DM support so it can be called from bluesky or pyepics
Transitional support for use in bluesky *and* SPEC, refactor the DM support for use in either bluesky or pyepics.  Will need PyEpics structure similar to what is in 35-DM-support.py that uses `epics.PV` instead of `EpicsSignal`.

* [x] build data structure
* [x] write the workflow file
* [x] execute the workflow from SPEC
* [x] execute the workflow from bluesky

### PR DESCRIPTION
**Pull request by prjemian**
fixes #36

### CODE REVIEW

**Comment by prjemian** [comment]
do not merge yet - not ready for review either

**Comment by prjemian** [comment]
needs testing with bluesky that it still works

**Comment by sureshnaps** [comment]
@prjemian i am testing spec macros calling your py helper process. The .hdf made by you and the old way are identical. h5diff showed 13 h5diff's and they are just because of some are float32 in the old and float64 in the new. I call it success and have no intention to change this datatype.

Will turn off old .hdf generation with a flag next.

Testing transfer now (some issue with the server)
Will test analysis next.

**Comment by prjemian** [comment]
Great!  I added a couple notes:

* [how to keep the helper running](https://github.com/aps-8id-trr/ipython-8idiuser/issues/36#issuecomment-533663304) 
* [how to watch the register PVs for the helper](https://github.com/aps-8id-trr/ipython-8idiuser/issues/36#issuecomment-533631342)

**Comment by sureshnaps** [comment]
@prjemian I ran a lot of tests. Transfer always worked. When set to analysis, it was not working, the state changes from 0 to 1 to 0 but I do not see the DM process. I could not figure out where the helper is running to see the logs.

Then, I found that the flag that starts metadata is stuck at 1 and helper is indeed alive.

There is a valid set of values in the registers and this can be tested by changing the register values.

**Comment by sureshnaps** [comment]
@prjemian When you get a chance, can you please take a look at why the start/stop metadata Reg PV is always stuck at 1, helper seems alive.

**Comment by prjemian** [comment]
8idi:Reg170 is 0.0 now, I'll set it to 1 now and see what happens.

**Comment by prjemian** [comment]
Went from 1 back to 0 in the pvview window.  Logs show that two workflows executed, in sequence.

```
|2019-09-23 17:03:55.114|INFO|spec_DM_support|spec_DM_support|273|MainThread| - before starting data management workflow
|2019-09-23 17:03:55.293|INFO|spec_DM_support|spec_DM_support|278|MainThread| - after starting data management workflow (0.178s)
|2019-09-23 17:03:55.295|INFO|spec_DM_support|spec_DM_support|279|MainThread| - workflow file: /home/8-id-i/2019-3/deleteme201909/D019/D019_0001-0100__004.hdf
|2019-09-23 17:03:55.335|INFO|spec_DM_support|spec_DM_support|273|MainThread| - before starting data management workflow
|2019-09-23 17:03:55.375|INFO|spec_DM_support|spec_DM_support|278|MainThread| - after starting data management workflow (0.039s)
|2019-09-23 17:03:55.375|INFO|spec_DM_support|spec_DM_support|279|MainThread| - workflow file: /home/8-id-i/2019-3/deleteme201909/D019/D019_0001-0100__005.hdf
```

**Comment by prjemian** [comment]
That was a *transfer* workflow (8idiReg172 = 0)

**Comment by prjemian** [comment]
Is it OK to try an analysis (8idiReg172 = 1) workflow now?  Wasn't that the workflow that did not reset the trigger (8idi:Reg170) back to 0?

**Comment by sureshnaps** [comment]
yes it is ok to try either transfer or analysis, the latter is what did not work and got the state stuck at 1

**Comment by prjemian** [comment]
This time it worked!  Set 8idi:Reg172 to 1 (analysis), then set 8idi:Reg170 to 1 (trigger) which went back to 0 shortly.  See the logs and screen capture.

```
|2019-09-23 17:38:12.072|INFO|spec_DM_support|spec_DM_support|273|MainThread| - before starting data management workflow
|2019-09-23 17:38:12.218|INFO|spec_DM_support|spec_DM_support|278|MainThread| - after starting data management workflow (0.146s)
|2019-09-23 17:38:12.219|INFO|spec_DM_support|spec_DM_support|279|MainThread| - workflow file: /home/8-id-i/2019-3/deleteme201909/D019/D019_0001-0100__006.hdf
```

Clipboard01

**Comment by prjemian** [comment]
Again, the same:

```snow% camonitor 8idi:Reg170.{DESC,VAL}
8idi:Reg170.DESC               2019-09-23 17:38:12.233616 start/stop metadata  
8idi:Reg170.VAL                2019-09-23 17:38:12.233616 0  
8idi:Reg170.VAL                2019-09-23 17:44:44.347993 1  
8idi:Reg170.VAL                2019-09-23 17:44:44.481327 0  
```

```
|2019-09-23 17:44:44.361|INFO|spec_DM_support|spec_DM_support|273|MainThread| - before starting data management workflow
|2019-09-23 17:44:44.487|INFO|spec_DM_support|spec_DM_support|278|MainThread| - after starting data management workflow (0.126s)
|2019-09-23 17:44:44.488|INFO|spec_DM_support|spec_DM_support|279|MainThread| - workflow file: /home/8-id-i/2019-3/deleteme201909/D019/D019_0001-0100__007.hdf
```

**Comment by sureshnaps** [comment]
I see 2 transfers on the workflow screen. I do not see the 1 analysis appearing on the workflow. next time, can you paste the uuid of the dm command?

**Comment by prjemian** [comment]
Not sure I know how to get that.  Is it in a PV?  I'm not getting the log output from the analysis process now.

**Comment by sureshnaps** [comment]
when dm command is run, the stdout from that is logged or printed I think.

**Comment by prjemian** [comment]
Right.  Somehow, this part is not working as planned.  Need to debug that.

**Comment by prjemian** [comment]
*I* need to debug that.  Thought I had a fix in place.

**Comment by prjemian** [comment]
@sureshnaps , @qzhang234 , @ericmdufresne : With these [comments](https://github.com/aps-8id-trr/ipython-8idiuser/issues/36#issuecomment-535992061), I believe this PR is ready to merge this morning.  Any objections?

**Pull request merged**
