### PR TITLE
wa should work even when motor is disconnected

### PR DESCRIPTION
**Pull request by prjemian**
fixes #210

### CODE REVIEW

**Comment by prjemian** [comment]
@qzhang234 : bump

**Comment by prjemian** [comment]
Should this be closed without merge?

**Comment by qzhang234** [comment]
Yes I agree. Should I click `Resolve conflict` or simply `Close with comment`?

image

**Comment by prjemian** [comment]
Close with comment (unless you actually plan to modify the code to resolve the conflict).

**Pull request closed without merging**
